### ISSUE TITLE
Travis build failing

### ISSUE THREAD

**Issue by spiegela** [codedellemc/ecs-cf-service-broker#75]
The travis tests are currently failing.  I believe it's due to the Codacy integration, which needs to be updated. Here is the expected updates to the `before_script` and `after_script` for the travis config below, but I will need to word the the {code} team to generate updated Codacy encrypted env vars.

```yaml
before_script:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
after_script:
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
```
